# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gX2W2TZdiyxnuskbIVVs1Mqu3EWUq94L
"""

!pip install pandasql

import pandas as pd
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

print("Cabos passado e sistema elétrico instalado com sucesso!")

dados_lojas = {
    'id_loja': [1, 2, 3],
    'nome_loja': ['Bravos Paulista', 'Bravos Shopping Metrô', 'Bravos Delivery'],
    'modelo_negocio': ['Avenida', 'Shopping', 'Delivery'],
    'custo_fixo_aluguel': [15000.00, 25000.00, 5000.00]
}
lojas = pd.DataFrame(dados_lojas)

dados_produtos = {
    'id_produto': [101, 102],
    'nome_produto': ['Bravos Premium Burguer','Batata Frita Tradicional'],
    'custo_cmv': [7.10, 2.50],
    'preco_venda': [29.90, 12.00]
}
produtos = pd.DataFrame(dados_produtos)

print("--- TABELA DE LOJAS CADASTRADAS ---")
print(lojas)
print("\n--- TABELA DE PRODUTOS NO CARDÁPIO ---")
print(produtos)

dados_venda = {
    'id_pedido': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'id_loja': [1, 1,  2, 2, 3, 3, 3],
    'id_produto': [101, 102, 101, 101, 101, 102, 101],
    'quantidade': [2, 1, 5, 3, 1, 2, 4],
    'forma_pagamento': ['Pix', 'Dinheiro', 'Cartao', 'Cartao', 'Pix', 'Cartao', 'Pix']
}
vendas = pd.DataFrame(dados_venda)

print("--- TABELA DE VENDAS REGISTRADAS NO CAIXA ---")
print(vendas)

consulta_sql = """
SELECT
    v.id_pedido,
    v.quantidade,
    p.nome_produto,
    p.preco_venda,
    (v.quantidade * p.preco_venda) AS faturamento_pedido
FROM vendas v
JOIN produtos p ON v.id_produto = p.id_produto;
"""

resultado = pysqldf(consulta_sql)
print("--- RELATÓRIO ESTRATÉGICO GERADO VIA SQL ---")
resultado

# Consulta SQL Avançada: Agrupando o faturamento por Modelo de Negócio
consulta_diretoria = """
SELECT
    l.modelo_negocio,
    SUM(v.quantidade) AS total_itens_vendidos,
    SUM(v.quantidade * p.preco_venda) AS faturamento_total,
    SUM(v.quantidade * p.custo_cmv) AS custo_total_insumos,
    SUM(v.quantidade * p.preco_venda) - SUM(v.quantidade * p.custo_cmv) AS lucro_bruto_total
FROM vendas v
JOIN lojas l ON v.id_loja = l.id_loja
JOIN produtos p ON v.id_produto = p.id_produto
GROUP BY l.modelo_negocio
ORDER BY lucro_bruto_total DESC;
"""

# Executando a nova consulta
relatorio_final = pysqldf(consulta_diretoria)
print("--- RELATÓRIO PREENCHIDO PARA A DIRETORIA ---")
relatorio_final

# 1. Rodando a consulta da diretoria para garantir que ela exista na memória agora
consulta_diretoria = """
SELECT
    l.modelo_negocio,
    SUM(v.quantidade) AS total_itens_vendidos,
    SUM(v.quantidade * p.preco_venda) AS faturamento_total,
    SUM(v.quantidade * p.custo_cmv) AS custo_total_insumos,
    SUM(v.quantidade * p.preco_venda) - SUM(v.quantidade * p.custo_cmv) AS lucro_bruto_total
FROM vendas v
JOIN lojas l ON v.id_loja = l.id_loja
JOIN produtos p ON v.id_produto = p.id_produto
GROUP BY l.modelo_negocio
ORDER BY lucro_bruto_total DESC;
"""
relatorio_final = pysqldf(consulta_diretoria)

# 2. Exportando TODOS os arquivos de uma vez só!
lojas.to_csv('tabela_lojas.csv', index=False)
produtos.to_csv('tabela_produtos.csv', index=False)
vendas.to_csv('tabela_vendas.csv', index=False)
relatorio_final.to_csv('tabela_resultado_diretoria.csv', index=False)

print("📦 TUDO PRONTO! Arquivos empacotados no container com sucesso!")
print("📥 Agora vá na pastinha do lado esquerdo e faça o download dos arquivos!")